//! SeaORM Entity. Generated by sea-orm-codegen 0.9.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "response_type")]
pub enum ResponseType {
    #[sea_orm(string_value = "code")]
    Code,
    #[sea_orm(string_value = "other")]
    Other,
}
