version: "3"

services:
  oauth:
    build: .
    volumes:
      - ../:/app:cached
    ports:
      - 8080:8080
    networks:
      - oauth
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - oauth
    volumes:
      - post-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Oauth

volumes:
  post-db:

networks:
  oauth:
